{
  "highlevel": 238,
  "local_port": 8090,
  "go1_ip": "192.168.50.41",
  "go1_port": 8082,
  "go1_unity_ip": "192.168.50.246",
  "unity_state_port": 15101,
  "unity_cmd_port": 15102,
  "unity_rx_port": 15100,
  "unity_waypoint_tx_port": 15104,
  "unity_path_port": 15110,
  "go1_ap_ip": "192.168.123.161",
  "aruco_udp_port": 5008,
  "server_upload_url": "http://210.110.250.33:7864/upload",
  "state_change_url": "http://210.110.250.33:7864/state_change",
  "state_change_interval_sec": 0.2,
  "json_cmd_url": "http://127.0.0.1:7864/cmd"
}
